# Generated by Django 3.2.25 on 2024-07-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name': 'Restaurante', 'verbose_name_plural': 'Restaurantes'},
        ),
    ]
