# Generated by Django 3.2.25 on 2024-07-19 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0004_auto_20240719_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('status', models.CharField(default='p', max_length=2, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_clientes', related_query_name='pagamento_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_reservas', related_query_name='pagamento_reserva', to='reservas.reserva', verbose_name='Reserva')),
            ],
        ),
    ]
