# Generated by Django 3.2.25 on 2024-07-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('status', models.CharField(choices=[('f', 'finalizado'), ('c', 'cancelado'), ('p', 'pendente'), ('pr', 'processando')], default='p', max_length=2, verbose_name='Status')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pagamento_reservas', related_query_name='pagamento_reserva', to='reservas.reserva', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Pagamento',
            },
        ),
    ]
