# Generated by Django 3.2.25 on 2024-07-19 20:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20240719_1520'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pagamentos',
            new_name='Pagamento',
        ),
        migrations.AlterModelOptions(
            name='pagamento',
            options={'verbose_name': 'Pagamento'},
        ),
    ]
