# Generated by Django 3.2.25 on 2024-07-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20240719_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cliente',
        ),
    ]
