# Generated by Django 3.2.25 on 2025-10-24 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20251023_2142'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_auto_20251021_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='clients.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_charge_id',
            field=models.CharField(blank=True, db_index=True, help_text='Charge ID from the payment gateway after successful payment', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='Customer ID from the payment gateway', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Payment Intent ID from the payment gateway', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method_type',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('bank_transfer', 'Bank Transfer'), ('pix', 'Pix'), ('unknown', 'Unknown')], default='unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
