# Generated by Django 3.2.25 on 2025-11-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20251023_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway_payment_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='Session ID from the payment gateway', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
