# Generated by Django 3.2.25 on 2026-01-17 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_auto_20260117_0713'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0005_auto_20251222_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Valor total do pagamento em reais', max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(help_text='Cliente que realizou o pagamento', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Data e hora da criação do pagamento'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_charge_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da cobrança no gateway após o pagamento bem-sucedido (máximo 255 caracteres)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_customer_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID do cliente no gateway de pagamento (máximo 255 caracteres)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da intenção de pagamento no gateway (máximo 255 caracteres)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_payment_session_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID da sessão de pagamento no gateway (máximo 255 caracteres)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('unknown', 'Desconhecido')], default='unknown', help_text='Gateway de pagamento usado (ex: Stripe) (máximo 20 caracteres)', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method_type',
            field=models.CharField(choices=[('credit_card', 'Cartão de Crédito'), ('bank_transfer', 'Transferência Bancária'), ('pix', 'Pix'), ('unknown', 'Desconhecido')], default='unknown', help_text='Tipo de método de pagamento utilizado (máximo 20 caracteres)', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True, help_text='Motivo do reembolso, se realizado'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor reembolsado, se aplicável (10 dígitos, 2 casas decimais)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, help_text='Data e hora do reembolso', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reservation',
            field=models.ForeignKey(help_text='Reserva associada ao pagamento', on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='reservations.reservation'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluído'), ('failed', 'Falhou'), ('refunded', 'Reembolsado'), ('cancelled', 'Cancelado')], default='pending', help_text='Status atual do processamento do pagamento', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Última atualização do status do pagamento'),
        ),
    ]
