# Generated by Django 3.2.25 on 2026-01-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20260116_0335'),
        ('payments', '0006_auto_20260117_0713'),
    ]

    operations = [
    ]
