# Generated by Django 3.2.25 on 2026-01-23 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_auto_20260123_1915'),
        ('payments', '0007_merge_0006_auto_20260116_0335_0006_auto_20260117_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='refunded_amount',
        ),
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(blank=True, help_text='Price for this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_prices', to='reservations.price'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_price',
            field=models.ForeignKey(blank=True, help_text='Refunded price, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunded_payment_prices', to='reservations.price'),
        ),
    ]
