# Generated by Django 3.2.25 on 2026-01-23 19:16

from django.db import migrations


def populate_prices(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')
    Price = apps.get_model('reservations', 'Price')  # Assuming Price is in reservations

    # Create prices for payments
    for payment in Payment.objects.all():
        # Assume amount was Decimal
        value = int(float(payment.amount) * 100)
        price = Price.objects.create(currency='usd', value=value, active=True)
        payment.price = price
        payment.save()


def reverse_populate_prices(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0008_auto_20260123_1915'),
        (
            'reservations',
            '0014_auto_20260123_1915',
        ),  # Ensure reservations prices are created first
    ]

    operations = [
        migrations.RunPython(populate_prices, reverse_populate_prices),
    ]
