# Generated by Django 3.2.25 on 2026-01-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0009_populate_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name='payment_prices',
                to='reservations.price',
            ),
        ),
    ]
