# Generated by Django 3.2.25 on 2026-01-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_reservation_price'),
        ('payments', '0010_alter_price_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.ForeignKey(blank=True, help_text='Price for this payment', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_prices', to='reservations.price'),
        ),
    ]
