# Generated by Django 3.2.25 on 2026-01-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_alter_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('brl', 'BRL')], default='usd', help_text='Currency for the payment', max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('brl', 'BRL')], help_text='Currency of the refund', max_length=10, null=True, verbose_name='Refunded Currency'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Payment amount in cents', null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_price',
            field=models.PositiveIntegerField(blank=True, help_text='Refunded amount in cents', null=True, verbose_name='Refunded Price'),
        ),
    ]
