# Generated by Django 3.2.25 on 2026-01-23 23:07

from django.db import migrations


def populate_direct_fields(apps, schema_editor):
    Payment = apps.get_model('payments', 'Payment')

    for payment in Payment.objects.all():
        if hasattr(payment, 'price') and payment.price:  # FK exists
            price_obj = payment.price
            payment.currency = price_obj.currency
            payment.price = price_obj.value
            payment.save()


def reverse_populate_direct_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0012_auto_20260123_2307'),
    ]

    operations = [
        migrations.RunPython(populate_direct_fields, reverse_populate_direct_fields),
    ]
