# Generated by Django 3.2.25 on 2026-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('payments', '0013_populate_direct_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(
                default='usd',
                help_text='Currency for the payment',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='payment',
            name='price',
            field=models.PositiveIntegerField(
                help_text='Payment amount in cents',
            ),
        ),
    ]
