# Generated by Django 3.2.25 on 2024-07-26 00:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, validators=[django.core.validators.RegexValidator('[\\w\\s]+')], verbose_name='Nome')),
                ('presentation_text', models.TextField(max_length=500, unique=True, verbose_name='Nome')),
                ('logo', models.ImageField(upload_to='restaurantes/logo', verbose_name='Logo')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_restaurants', related_query_name='hotel_restaurant', to='home.hotel')),
            ],
        ),
    ]
