# Generated by Django 3.2.25 on 2024-07-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='presentation_text',
            field=models.TextField(max_length=500, unique=True, verbose_name='Apresentação'),
        ),
    ]
