[project]
name = "sistema-de-hotel"
version = "0.1.0"
description = ""
authors = [
    {name = "LeandroDeJesus-S",email = "jstleandro@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "amqp==5.2.0",
    "ansicon==1.89.0",
    "arrow==1.3.0",
    "asgiref==3.8.1",
    "billiard==4.2.0",
    "blessed==1.20.0",
    "certifi==2024.7.4",
    "chardet==5.2.0",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "click-didyoumean==0.3.1",
    "click-plugins==1.1.1",
    "click-repl==0.3.0",
    "colorama==0.4.6",
    "Django==3.2.25",
    "django-axes==6.5.1",
    "django-picklefield==3.2",
    "django-q==1.3.9",
    "fontawesomefree==6.6.0",
    "idna==3.7",
    "jinxed==1.2.1",
    "kombu==5.3.7",
    "pillow==10.4.0",
    "prompt_toolkit==3.0.47",
    "python-dateutil==2.9.0.post0",
    "python-dotenv==1.0.1",
    "pytz==2024.1",
    "redis==3.5.3",
    "reportlab==4.2.2",
    "requests==2.32.3",
    "setuptools==72.1.0",
    "six==1.16.0",
    "sqlparse==0.5.1",
    "stripe==10.3.0",
    "types-python-dateutil==2.9.0.20240316",
    "typing_extensions==4.12.2",
    "tzdata==2024.1",
    "urllib3==2.2.2",
    "vine==5.1.0",
    "wcwidth==0.2.13",
    "phonenumbers (>=9.0.13,<10.0.0)",
]

[tool.poetry]
package-mode = false


[tool.poetry.group.dev.dependencies]
mypy = "^1.17.1"
ruff = "^0.12.10"
taskipy = "^1.14.1"
bandit = {extras = ["toml"], version = "^1.8.6"}
types-requests = "^2.32.4.20250809"
pytest-django = "^4.11.1"
pytest-responses = "^0.5.1"
pytest-mock = "^3.14.1"
faker = "^37.6.0"
django-dynamic-fixture = "^4.0.1"

[tool.ruff]
line-length = 95
extend-exclude = [
	"*/migrations/*",
	"*__init__*",
	"*__pyc*",
    "media/",
    "templates/*",
    "readme",
    "tests/",
    "*_test.py",
    "manage.py"
]
indent-width = 4
output-format = "grouped"

[tool.ruff.lint]
preview = true
select = ['I', 'F', 'E', 'W', 'PL', 'PT']

[tool.ruff.format]
preview = true
quote-style = "single"
docstring-code-format = true
docstring-code-line-length = 90
line-ending = "lf"

[tool.taskipy.tasks]
lint = 'ruff check . --preview'
format = 'ruff check --fix && ruff format --target-version py39 --respect-gitignore'
run = 'python manage.py runserver'
typecheck = 'mypy . --ignore-missing-imports'

pre_test = 'task format && task typecheck'
test = 'python manage.py test'
post_test = 'task scan'

scan = 'bandit -c pyproject.toml -r .'

[tool.mypy]
exclude = [
	"migrations/*",
	"__init__*",
	"__pyc*",
    "media/",
    "templates/*",
    "readme",
    "tests/",
    "manage.py"
]
ignore_missing_imports = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
pretty = true

[tool.bandit]
exclude_dirs = [
    'tests',
    'media',
    'templates',
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "HOTEL.settings"
python_files = "*/test_*.py"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
