class PaymentRules:
    ALLOWED_METHODS = ['card', 'boleto']
    CHECKOUT_SESSION_EXPIRES_MIN = 30
    GATEWAY_FIELD_MAX_LEN = 255
    STATUS_MAX_LEN = 10
    METHOD_TYPE_MAX_LEN = 20
    GATEWAY_MAX_LEN = 20
    AMOUNT_MAX_DIGITS = 10
    AMOUNT_DECIMAL_PLACES = 2
    REFUND_AMOUNT_MAX_DIGITS = 10
    REFUND_AMOUNT_DECIMAL_PLACES = 2
