# Generated by Django 3.2.25 on 2024-08-17 03:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240729_1906'),
        ('services', '0002_alter_restaurant_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, validators=[django.core.validators.RegexValidator('[\\w\\s]+')], verbose_name='Nome')),
                ('presentation_text', models.TextField(max_length=500, unique=True, verbose_name='Apresentação')),
                ('logo', models.ImageField(upload_to='services/logo', verbose_name='Logo')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', related_query_name='hotel_service', to='home.hotel')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
