# Generated by Django 3.2.25 on 2024-08-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240729_1906'),
        ('services', '0003_auto_20240817_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', related_query_name='hotel_service', to='home.hotel'),
        ),
    ]
