# Generated by Django 3.2.25 on 2024-08-18 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240729_1906'),
        ('services', '0004_alter_services_hotel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
