# Generated by Django 3.2.25 on 2025-12-23 00:17

from django.db import migrations, models
import utils.adapters.image_validators


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(upload_to='services/logo', validators=[utils.adapters.image_validators.validate_service_logo], verbose_name='Logo'),
        ),
    ]
