# Generated by Django 3.2.25 on 2026-01-16 03:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import utils.adapters.image_validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20260116_0335'),
        ('services', '0006_alter_service_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AlterField(
            model_name='service',
            name='hotel',
            field=models.ForeignKey(help_text='Hotel to which the service belongs', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_services', related_query_name='hotel_service', to='home.hotel'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(help_text='Service logo image or icon', upload_to='services/logo', validators=[utils.adapters.image_validators.validate_service_logo], verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Unique name of the service offered by the hotel (maximum 45 characters)', max_length=45, unique=True, validators=[django.core.validators.RegexValidator('[\\w\\s]+')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='presentation_text',
            field=models.TextField(help_text='Descriptive text of the service (up to 500 characters)', max_length=500, unique=True, verbose_name='Presentation'),
        ),
    ]
