# Generated by Django 3.2.25 on 2024-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(default='2002-03-22', verbose_name='Data de nascimento'),
            preserve_default=False,
        ),
    ]
