# Generated by Django 3.2.25 on 2024-08-01 00:41

import clients.validators
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[clients.validators.CpfValidator(message='CPF inválido.')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'O nome deve conter apenas letras'), django.core.validators.MaxLengthValidator(25, 'Nome muito grande.'), django.core.validators.MinLengthValidator(2, 'Nome muito pequeno.')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'O sobrenome deve conter apenas letras'), django.core.validators.MinLengthValidator(2, 'Sobrenome muito pequeno.'), django.core.validators.MaxLengthValidator(50, 'Sobrenome muito grande.')], verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Informe um nome de usuário válido. O valor deve conter apenas letras, números e os seguintes caracteres @.+-_', 'null': 'Nome de usuário não pode ser vazio.', 'unique': 'Username já existe.'}, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Nome de usuário deve ter de 2 a 150 caracteres.'), django.core.validators.MaxLengthValidator(150, 'Nome de usuário deve ter de 2 a 150 caracteres.'), django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
