# Generated by Django 3.2.25 on 2025-11-17 15:03

import clients.infra.validators
import clients.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_auto_20240817_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(validators=[clients.infra.validators.BirthDateValidator.validate], verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'CPF não disponível.'}, help_text='Seu CPF sem pontuação', max_length=11, unique=True, validators=[clients.validators.CpfValidator(message='CPF inválido.')], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Por favor, preencha o campo de e-mail.', 'invalid': 'Por favor, insira um endereço de e-mail válido.', 'null': 'Por favor, preencha o campo de e-mail.', 'unique': 'E-mail não disponível.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('^[^\\W\\d_]+$', 'O nome deve conter apenas letras.'), django.core.validators.MaxLengthValidator(25, 'Nome muito longo.'), django.core.validators.MinLengthValidator(2, 'Nome muito curto.')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[^\\W\\d_ ]+(?: [^\\W\\d_]+)*$', 'O sobrenome deve conter apenas letras e espaços.'), django.core.validators.MinLengthValidator(2, 'Sobrenome muito curto.'), django.core.validators.MaxLengthValidator(50, 'Sobrenome muito longo.')], verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(error_messages={'blank': 'O telefone não pode estar vazio.', 'invalid': 'Número de telefone inválido.', 'null': 'O telefone não pode estar vazio.', 'unique': 'Número de telefone não disponível.'}, max_length=16, unique=True, validators=[clients.infra.validators.PhoneNumberValidator.validate], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'blank': 'O nome de usuário não pode estar vazio.', 'invalid': 'Por favor, insira um nome de usuário válido. O valor deve conter apenas letras, números e os seguintes caracteres @.+-_', 'null': 'O nome de usuário não pode estar vazio.', 'unique': 'Nome de usuário já existe.'}, max_length=150, unique=True, validators=[clients.infra.validators.UsernameValidator.validate], verbose_name='username'),
        ),
    ]
