# Generated by Django 3.2.25 on 2025-12-23 00:17

import clients.infra.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20251222_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(validators=[clients.infra.validators.BirthDateValidator.validate], verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(error_messages={'blank': 'O telefone não pode estar vazio.', 'invalid': 'Número de telefone inválido.', 'null': 'O telefone não pode estar vazio.', 'unique': 'Número de telefone não disponível.'}, max_length=16, unique=True, validators=[clients.infra.validators.PhoneNumberValidator.validate], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'blank': 'O nome de usuário não pode estar vazio.', 'invalid': 'Por favor, insira um nome de usuário válido. O valor deve conter apenas letras, números e os seguintes caracteres @.+-_', 'null': 'O nome de usuário não pode estar vazio.', 'unique': 'Nome de usuário já existe.'}, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'O nome de usuário deve ter de 2 a 150 caracteres.'), django.core.validators.MaxLengthValidator(150, 'O nome de usuário deve ter de 2 a 150 caracteres.'), clients.infra.validators.UsernameValidator.validate], verbose_name='username'),
        ),
    ]
