# Generated by Django 3.2.25 on 2026-01-17 07:13

import clients.infra.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_auto_20251225_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(help_text='Birth date in YYYY-MM-DD format', validators=[clients.infra.validators.BirthDateValidator.validate], verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'CPF not available.'}, help_text='Your CPF without punctuation (maximum 11 characters)', max_length=11, unique=True, validators=[clients.infra.validators.CpfValidator.validate], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Please fill in the email field.', 'invalid': 'Please enter a valid email address.', 'null': 'Please fill in the email field.', 'unique': 'Email not available.'}, help_text="Client's unique email address (maximum 255 characters)", max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(help_text="Client's first name, only letters and spaces (maximum 25 characters)", max_length=25, validators=[django.core.validators.RegexValidator('^[^\\W\\d_]+$', 'First name must contain only letters.'), django.core.validators.MaxLengthValidator(25, 'First name is too long.'), django.core.validators.MinLengthValidator(2, 'First name is too short.')], verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(help_text="Client's last name, only letters and spaces (maximum 50 characters)", max_length=50, validators=[django.core.validators.RegexValidator('^[^\\W\\d_ ]+(?: [^\\W\\d_]+)*$', 'Surname must contain only letters and spaces.'), django.core.validators.MinLengthValidator(2, 'Surname is too short.'), django.core.validators.MaxLengthValidator(50, 'Surname is too long.')], verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(error_messages={'blank': 'The phone number cannot be empty.', 'invalid': 'Invalid phone number.', 'null': 'The phone number cannot be empty.', 'unique': 'Phone number not available.'}, help_text='Phone number in (XX) XXXXX-XXXX format (maximum 25 characters)', max_length=25, unique=True, validators=[clients.infra.validators.PhoneNumberValidator.validate], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'blank': 'The username cannot be empty.', 'invalid': 'Please enter a valid username. The value must contain only letters, numbers, and the following characters @.+-_', 'null': 'The username cannot be empty.', 'unique': 'Username already exists.'}, help_text='Unique username for login, must be between 2 and 150 characters', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Username must be between 2 and 150 characters long.'), django.core.validators.MaxLengthValidator(150, 'Username must be between 2 and 150 characters long.'), clients.infra.validators.UsernameValidator.validate], verbose_name='username'),
        ),
    ]
