# Generated by Django 3.2.25 on 2026-01-23 19:15

import clients.infra.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_auto_20260123_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birthdate',
            field=models.DateField(help_text='Birth date in YYYY-MM-DD format', validators=[clients.infra.validators.BirthDateValidator.validate], verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(error_messages={'unique': 'CPF not available.'}, help_text='Your CPF without punctuation (maximum 11 characters)', max_length=11, unique=True, validators=[clients.infra.validators.CpfValidator.validate], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(error_messages={'blank': 'The phone number cannot be empty.', 'invalid': 'Invalid phone number.', 'null': 'The phone number cannot be empty.', 'unique': 'Phone number not available.'}, help_text='Phone number in (XX) XXXXX-XXXX format (maximum 25 characters)', max_length=25, unique=True, validators=[clients.infra.validators.PhoneNumberValidator.validate], verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='username',
            field=models.CharField(error_messages={'blank': 'The username cannot be empty.', 'invalid': 'Please enter a valid username. The value must contain only letters, numbers, and the following characters @.+-_', 'null': 'The username cannot be empty.', 'unique': 'Username already exists.'}, help_text='Unique username for login, must be between 2 and 150 characters', max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Username must be between 2 and 150 characters long.'), django.core.validators.MaxLengthValidator(150, 'Username must be between 2 and 150 characters long.'), clients.infra.validators.UsernameValidator.validate], verbose_name='username'),
        ),
    ]
