# Generated by Django 3.2.25 on 2024-07-29 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('short_desc', models.CharField(max_length=100, unique=True, verbose_name='Descrição curta')),
                ('icon', models.ImageField(blank=True, help_text='ícone com tamanho 32x32', null=True, upload_to='', verbose_name='Ícone')),
                ('displayable_on_homepage', models.BooleanField(default=False, verbose_name='Visível na página inicial')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[\\w ]+$', 'Nome da classe é inválido.')], verbose_name='Classe')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}[A-Z]?$')], verbose_name='Número')),
                ('adult_capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5, 'Quantidade de adultos excedida. (max: 5)'), django.core.validators.MinValueValidator(1, 'Quantidade de adultos insuficiente. (min: 1)')], verbose_name='Capacidade de adultos')),
                ('child_capacity', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3, 'Quantidade de crianças excedida. (max: 3)'), django.core.validators.MinValueValidator(0, 'Quantidade de crianças insuficiente. (min: 0)')], verbose_name='Capacidade crianças')),
                ('size', models.FloatField(validators=[django.core.validators.MinValueValidator(2, 'O quarto é muito pequeno. (min: 2)'), django.core.validators.MaxValueValidator(30, 'O quarto é muito grande. (max: 30)')], verbose_name='Tamanho m²')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100, 'O valor do quarto deve ser de no mínimo R$100.00.'), django.core.validators.MaxValueValidator(500, 'O valor do quarto deve ser de no máximo R$500.00.')], verbose_name='Diária')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Somete jpg ou png'), django.core.validators.validate_image_file_extension], verbose_name='Imagem')),
                ('short_desc', models.CharField(max_length=255, unique=True, verbose_name='Descrição curta')),
                ('long_desc', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Descrição longa')),
                ('benefit', models.ManyToManyField(related_name='room_benefits', related_query_name='room_benefit', to='reservations.Benefit', verbose_name='Benefícios')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', related_query_name='hotel_room', to='home.hotel')),
                ('room_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_quartos', related_query_name='class_room', to='reservations.class')),
            ],
            options={
                'verbose_name': 'Quarto',
                'verbose_name_plural': 'Quartos',
                'ordering': ['-available'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin', models.DateField(verbose_name='Check-in')),
                ('checkout', models.DateField(verbose_name='Check-out')),
                ('observations', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('[\\w\\s]*')], verbose_name='Observações')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor total da reserva')),
                ('active', models.BooleanField(default=False, verbose_name='Ativa')),
                ('status', models.CharField(choices=[('I', 'iniciada'), ('P', 'processando'), ('A', 'ativa'), ('C', 'cancelada'), ('F', 'finalizada'), ('S', 'agendada')], default='I', max_length=2, verbose_name='Status')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_clients', related_query_name='reservation_client', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_rooms', related_query_name='reservation_room', to='reservations.room')),
            ],
        ),
    ]
