# Generated by Django 3.2.25 on 2024-07-29 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(blank=True, help_text='ícone com tamanho 32x32', null=True, upload_to='benefits/icon', verbose_name='Ícone'),
        ),
    ]
