# Generated by Django 3.2.25 on 2024-08-18 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_class_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(blank=True, help_text='ícone com tamanho 64x64', null=True, upload_to='benefits/icon', verbose_name='Ícone'),
        ),
    ]
