# Generated by Django 3.2.25 on 2025-09-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_benefit_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='active',
        ),
    ]
