# Generated by Django 3.2.25 on 2025-09-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_remove_reservation_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='adult_capacity',
            new_name='adults_capacity',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='child_capacity',
            new_name='children_capacity',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('I', 'iniciada'), ('P', 'processando'), ('A', 'ativa'), ('C', 'cancelada'), ('F', 'finalizada'), ('S', 'agendada')], default='I', max_length=1, verbose_name='Status'),
        ),
    ]
