# Generated by Django 3.2.25 on 2025-09-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_auto_20250922_1906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='benefit',
            new_name='benefits',
        ),
    ]
