# Generated by Django 3.2.25 on 2025-09-24 22:33

import datetime
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_rename_benefit_room_benefits'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('checkin__lte', django.db.models.expressions.F('checkout'))), name='checkin_check'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('checkout__gte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('checkin'), '+', django.db.models.expressions.Value(datetime.timedelta(days=1))))), name='min_stayed_days'),
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('checkout__lte', django.db.models.expressions.CombinedExpression(django.db.models.expressions.F('checkin'), '+', django.db.models.expressions.Value(datetime.timedelta(days=30))))), name='max_stayed_days'),
        ),
    ]
