# Generated by Django 3.2.25 on 2025-10-24 00:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20250924_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\- ]+$', 'O nome do benefício não pode conter caracteres especiais.')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='observations',
            field=models.TextField(blank=True, default='', max_length=100, validators=[django.core.validators.RegexValidator('[\\w\\s]*')], verbose_name='Observações'),
            preserve_default=False,
        ),
    ]
