# Generated by Django 3.2.25 on 2025-12-23 00:17

from django.db import migrations, models
import utils.adapters.image_validators


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_auto_20251023_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Motivo do cancelamento'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cancelada em'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(blank=True, help_text='ícone com tamanho 64x64', null=True, upload_to='benefits/icon', validators=[utils.adapters.image_validators.validate_benefit_icon], verbose_name='Ícone'),
        ),
    ]
