# Generated by Django 3.2.25 on 2026-01-16 03:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.adapters.image_validators


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20260116_0335'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservations', '0010_auto_20251222_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'Benefit', 'verbose_name_plural': 'Benefits'},
        ),
        migrations.AlterModelOptions(
            name='class',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'Reservation', 'verbose_name_plural': 'Reservations'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-available'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterField(
            model_name='benefit',
            name='displayable_on_homepage',
            field=models.BooleanField(default=False, help_text='If checked, the benefit will be displayed on the homepage', verbose_name='Visible on homepage'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='icon',
            field=models.ImageField(blank=True, help_text='icon with size 64x64', null=True, upload_to='benefits/icon', validators=[utils.adapters.image_validators.validate_benefit_icon], verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='name',
            field=models.CharField(help_text='Unique name of the benefit offered by the room', max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[\\w\\- ]+$', 'The benefit name cannot contain special characters.')], verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='benefit',
            name='short_desc',
            field=models.CharField(help_text='Brief description of the benefit (up to 100 characters)', max_length=100, unique=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(help_text='Room class name (e.g., Standard, Deluxe)', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\w[\\w ]*$', 'Class name is invalid.')], verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total calculated reservation amount in dollars', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Total reservation amount'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for reservation cancellation', verbose_name='Cancellation reason'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='Date and time of cancellation, if applicable', null=True, verbose_name='Cancelled at'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkin',
            field=models.DateField(help_text='Check-in date in YYYY-MM-DD format', verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout',
            field=models.DateField(help_text='Check-out date in YYYY-MM-DD format', verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='client',
            field=models.ForeignKey(help_text='Client who made the reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_clients', related_query_name='reservation_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time of reservation creation', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='observations',
            field=models.TextField(blank=True, help_text='Additional observations about the reservation (maximum 100 characters)', max_length=100, validators=[django.core.validators.RegexValidator('[\\w\\s]*')], verbose_name='Observations'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(blank=True, help_text='Reserved room', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_rooms', related_query_name='reservation_room', to='reservations.room'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('I', 'initialized'), ('P', 'processing'), ('A', 'active'), ('C', 'cancelled'), ('F', 'finished'), ('S', 'scheduled')], default='I', help_text='Current reservation status', max_length=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='room',
            name='adults_capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of adults the room can accommodate (between 1 and 5)', validators=[django.core.validators.MaxValueValidator(5, 'Adults capacity exceeded. (max: 5)'), django.core.validators.MinValueValidator(1, 'Insufficient adults. (min: 1)')], verbose_name='Adults capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True, help_text='If checked, the room is available for reservations', verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='room',
            name='benefits',
            field=models.ManyToManyField(help_text='Benefits offered by this room', related_name='room_benefits', related_query_name='room_benefit', to='reservations.Benefit', verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='room',
            name='children_capacity',
            field=models.PositiveSmallIntegerField(default=1, help_text='Maximum number of children the room can accommodate (between 0 and 3)', validators=[django.core.validators.MaxValueValidator(3, 'Children capacity exceeded. (max: 3)'), django.core.validators.MinValueValidator(0, 'Insufficient children. (min: 0)')], verbose_name='Children capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, help_text='Daily rate price in dollars (between 100 and 500)', max_digits=10, validators=[django.core.validators.MinValueValidator(100, 'The room price must be at least $100.00.'), django.core.validators.MaxValueValidator(500, 'The room price must be at most $500.00.')], verbose_name='Daily rate'),
        ),
        migrations.AlterField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(help_text='Hotel to which the room belongs', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_rooms', related_query_name='hotel_room', to='home.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Main room image (accepted formats: JPG, PNG)', null=True, upload_to='%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Only jpg or png'), django.core.validators.validate_image_file_extension], verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='room',
            name='long_desc',
            field=models.TextField(blank=True, help_text='Detailed description of the room (up to 1000 characters)', max_length=1000, null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='number',
            field=models.CharField(help_text='Unique room number (e.g., 101, 102A, maximum 4 characters)', max_length=4, unique=True, validators=[django.core.validators.RegexValidator('^\\d{3}[A-Z]?$')], verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_class',
            field=models.ForeignKey(help_text='Class to which the room belongs', on_delete=django.db.models.deletion.DO_NOTHING, related_name='class_quartos', related_query_name='class_room', to='reservations.class'),
        ),
        migrations.AlterField(
            model_name='room',
            name='short_desc',
            field=models.CharField(help_text='Short description of the room (up to 255 characters)', max_length=255, unique=True, verbose_name='Short description'),
        ),
        migrations.AlterField(
            model_name='room',
            name='size',
            field=models.FloatField(help_text='Room size in square meters (between 2 and 30)', validators=[django.core.validators.MinValueValidator(2, 'The room is too small. (min: 2)'), django.core.validators.MaxValueValidator(30, 'The room is too large. (max: 30)')], verbose_name='Size m²'),
        ),
    ]
