# Generated by Django 3.2.25 on 2026-01-23 19:15

import django.core.validators
from decimal import Decimal

from django.db import migrations, models
import django.db.models.deletion


def populate_prices(apps, schema_editor):
    # Historical models before removal
    Room = apps.get_model('reservations', 'Room')
    Reservation = apps.get_model('reservations', 'Reservation')
    Price = apps.get_model('reservations', 'Price')

    # Create prices for rooms
    for room in Room.objects.all():
        value = int(float(room.daily_price) * 100)
        price = Price.objects.create(currency='usd', value=value, active=True)
        room.prices.add(price)

    # Create prices for reservations
    for reservation in Reservation.objects.all():
        value = int(float(reservation.amount) * 100)
        price = Price.objects.create(currency='usd', value=value, active=True)
        reservation.price = price
        reservation.save()


class Migration(migrations.Migration):
    dependencies = [
        ('reservations', '0013_merge_0011_auto_20260116_0335_0012_auto_20260117_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'currency',
                    models.CharField(
                        help_text='Currency code in lowercase ISO 4217 format (e.g., usd, eur)',
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                '^[a-z]{3}$', 'Currency must be 3 lowercase letters'
                            )
                        ],
                        verbose_name='Currency',
                    ),
                ),
                (
                    'value',
                    models.PositiveIntegerField(
                        help_text='Price value in cents', verbose_name='Value'
                    ),
                ),
                (
                    'active',
                    models.BooleanField(
                        default=True,
                        help_text='Whether this price is available for use',
                        verbose_name='Active',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.RunPython(populate_prices, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='reservation',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='room',
            name='daily_price',
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(
                blank=True,
                help_text='Price for this reservation',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reservation_prices',
                related_query_name='reservation_price',
                to='reservations.price',
            ),
        ),
        migrations.AddField(
            model_name='room',
            name='prices',
            field=models.ManyToManyField(
                blank=True,
                help_text='Prices for this room in different currencies',
                related_name='room_prices',
                to='reservations.Price',
            ),
        ),
    ]
