# Generated by Django 3.2.25 on 2026-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reservations', '0014_auto_20260123_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(
                on_delete=models.SET_NULL,
                related_name='reservation_prices',
                related_query_name='reservation_price',
                to='reservations.price',
            ),
        ),
    ]
