# Generated by Django 3.2.25 on 2026-01-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_price_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.ForeignKey(blank=True, help_text='Price for this reservation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_prices', related_query_name='reservation_price', to='reservations.price'),
        ),
    ]
