# Generated by Django 3.2.25 on 2026-01-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD'), ('brl', 'BRL')], default='usd', help_text='Currency for the reservation', max_length=10, null=True, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.PositiveIntegerField(blank=True, help_text='Total reservation price in cents', null=True, verbose_name='Price'),
        ),
    ]
