# Generated by Django 3.2.25 on 2026-01-23 23:07

from django.db import migrations


def populate_direct_fields(apps, schema_editor):
    Reservation = apps.get_model('reservations', 'Reservation')

    for reservation in Reservation.objects.all():
        if reservation.price_id:  # Has FK
            price_obj = reservation.price  # Assuming historical model has it
            reservation.currency = price_obj.currency
            reservation.price = price_obj.value
            reservation.save()


def reverse_populate_direct_fields(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('reservations', '0018_auto_20260123_2307'),
    ]

    operations = [
        migrations.RunPython(populate_direct_fields, reverse_populate_direct_fields),
    ]
