# Generated by Django 3.2.25 on 2026-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('reservations', '0019_populate_direct_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='currency',
            field=models.CharField(
                default='usd',
                help_text='Currency for the reservation',
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Total reservation price in cents',
                null=True,
            ),
        ),
    ]
