# Generated by Django 3.2.25 on 2026-01-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_auto_20260126_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('brl', 'BRL')], help_text='Currency for this price', max_length=3, verbose_name='Currency'),
        ),
    ]
