# Generated by Django 3.2.25 on 2024-07-29 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotéis'},
        ),
    ]
