# Generated by Django 3.2.25 on 2024-07-26 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(max_length=255, unique=True, verbose_name='Whatsapp'),
        ),
    ]
