# Generated by Django 3.2.25 on 2026-01-16 03:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240729_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'Hotels'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(help_text='Hotel contact email (maximum 155 characters)', max_length=155, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook',
            field=models.CharField(help_text='Facebook page URL or name', max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='hotel',
            field=models.OneToOneField(help_text='Hotel to which these contacts belong', on_delete=django.db.models.deletion.CASCADE, related_name='hotel_contacts', related_query_name='hotel_contact', to='home.hotel', verbose_name='Hotel'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram',
            field=models.CharField(help_text='Instagram username (without @, maximum 255 characters)', max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='Hotel landline phone', max_length=11, unique=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='twitter',
            field=models.CharField(help_text='Twitter username (without @, maximum 255 characters)', max_length=255, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(help_text='WhatsApp number for customer service (maximum 255 characters)', max_length=255, unique=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='icon',
            field=models.ImageField(help_text='Small hotel icon (recommended: square format)', upload_to='hotel/icon', verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(help_text='Hotel logo image (recommended: transparent PNG)', upload_to='hotel/logo', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='name',
            field=models.CharField(help_text='Unique name of the hotel', max_length=45, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='presentation_text',
            field=models.TextField(help_text='Hotel description text displayed on the homepage, up to 1000 characters', max_length=1000, verbose_name='Presentation text'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='slogan',
            field=models.CharField(help_text='Tagline displayed on the website', max_length=100, unique=True, verbose_name='Slogan'),
        ),
    ]
