# Generated by Django 3.2.25 on 2026-01-20 03:11

from django.db import migrations, models
import django.db.models.deletion


def migrate_contact_to_channels(apps, schema_editor):
    """Migrate existing Contact data to ContactChannel records."""
    Contact = apps.get_model('home', 'Contact')
    ContactChannel = apps.get_model('home', 'ContactChannel')

    for contact in Contact.objects.all():
        # Create email channel
        if contact.email:
            ContactChannel.objects.create(
                name='email',
                display_name='Email',
                html_icon='fa-regular fa-envelope',
                value=contact.email,
                display_value=contact.email,
                hotel=contact.hotel,
                active=False,  # As requested, none are active by default
            )

        # Create phone channel
        if contact.phone:
            ContactChannel.objects.create(
                name='phone',
                display_name='Phone',
                html_icon='fa-solid fa-phone',
                value=None,  # Phone numbers don't need URLs
                display_value=contact.phone,
                hotel=contact.hotel,
                active=False,
            )

        # Create WhatsApp channel
        if contact.whatsapp:
            ContactChannel.objects.create(
                name='whatsapp',
                display_name='WhatsApp',
                html_icon='fa-brands fa-whatsapp',
                value=f'https://wa.me/{contact.whatsapp}',  # Full URL as requested
                display_value=contact.whatsapp,
                hotel=contact.hotel,
                active=False,
            )

        # Create Instagram channel
        if contact.instagram:
            ContactChannel.objects.create(
                name='instagram',
                display_name='Instagram',
                html_icon='fa-brands fa-instagram',
                value=f'https://instagram.com/{contact.instagram}',
                display_value=f'@{contact.instagram}',
                hotel=contact.hotel,
                active=False,
            )

        # Create Facebook channel
        if contact.facebook:
            ContactChannel.objects.create(
                name='facebook',
                display_name='Facebook',
                html_icon='fa-brands fa-facebook',
                value=contact.facebook
                if contact.facebook.startswith('http')
                else f'https://facebook.com/{contact.facebook}',
                display_value=contact.facebook,
                hotel=contact.hotel,
                active=False,
            )

        # Create Twitter channel
        if contact.twitter:
            ContactChannel.objects.create(
                name='twitter',
                display_name='Twitter',
                html_icon='fa-brands fa-twitter',
                value=f'https://twitter.com/{contact.twitter}',
                display_value=f'@{contact.twitter}',
                hotel=contact.hotel,
                active=False,
            )


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0004_merge_0003_auto_20260116_0335_0003_auto_20260117_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='Short identifier name for the contact channel',
                        max_length=45,
                        unique=True,
                        verbose_name='Name',
                    ),
                ),
                (
                    'display_name',
                    models.CharField(
                        help_text='Name displayed to users',
                        max_length=45,
                        unique=True,
                        verbose_name='Display name',
                    ),
                ),
                (
                    'html_icon',
                    models.CharField(
                        blank=True,
                        help_text='HTML class name for the icon (e.g., fa-whatsapp)',
                        max_length=20,
                        null=True,
                        verbose_name='HTML icon',
                    ),
                ),
                (
                    'value',
                    models.TextField(
                        blank=True,
                        help_text='The actual URL or contact value',
                        null=True,
                        verbose_name='Value',
                    ),
                ),
                (
                    'display_value',
                    models.CharField(
                        help_text='User-friendly display value (e.g., phone number, @username)',
                        max_length=45,
                        unique=True,
                        verbose_name='Display value',
                    ),
                ),
                (
                    'active',
                    models.BooleanField(
                        default=False,
                        help_text='Whether this contact channel is available and displayed',
                        verbose_name='Active',
                    ),
                ),
                (
                    'hotel',
                    models.ForeignKey(
                        help_text='Hotel to which this contact channel belongs',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contact_channels',
                        to='home.hotel',
                        verbose_name='Hotel',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Contact channel',
                'verbose_name_plural': 'Contact channels',
            },
        ),
        migrations.RunPython(migrate_contact_to_channels, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
