"""
Django settings for HOTEL project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import dj_database_url
from django.contrib.messages import constants as msg
from dotenv import load_dotenv

load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.getenv('DEBUG', '0')))

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'clients',  # must be before auth to override createsuperuser command
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'axes',
    'fontawesomefree',
    'django_q',
    'home',
    'services',
    'reservations',
    'payments',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'axes.middleware.AxesMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'clients.authenticator.UserEmailAuthBackend',
]

ROOT_URLCONF = 'HOTEL.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.hotel',
                'django.template.context_processors.media',
                'home.context_processors.recaptcha',
            ],
        },
    },
]

WSGI_APPLICATION = 'HOTEL.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///db.sqlite3',
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'clients.infra.validators.DjangoPasswordValidatorAdapter',
    },
]

# user ath model
AUTH_USER_MODEL = 'clients.Client'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True
USE_TZ = True

DATE_FORMAT = 'N j, Y'
DATETIME_FORMAT = 'N j, Y, P'
SHORT_DATE_FORMAT = 'm/d/Y'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'static'
STATICFILES_DIRS = [BASE_DIR / 'templates/static']

# media
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# messages
MESSAGE_TAGS = {
    msg.DEBUG: 'alert-secondary',
    msg.INFO: 'alert-info',
    msg.SUCCESS: 'alert-success',
    msg.ERROR: 'alert-danger',
    msg.WARNING: 'alert-warning',
}

# session
SESSION_COOKIE_AGE = int(os.getenv('SESSION_COOKIE_AGE', str(60 * 60 * 24)))  # 1 day
SESSION_SAVE_EVERY_REQUEST = False
SESSION_COOKIE_HTTPONLY = True

# emails
EMAIL_BACKEND = os.environ['EMAIL_BACKEND']
EMAIL_HOST = os.environ['EMAIL_HOST']
EMAIL_PORT = os.environ['EMAIL_PORT']
USE_TLS = not DEBUG
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
EMAIL_SUBJECT_PREFIX = os.getenv('EMAIL_SUBJECT_PREFIX')


# Django Q
Q_CLUSTER = {
    'name': os.getenv('Q_CLUSTER_NAME', 'HOTEL'),
    'workers': int(os.getenv('Q_CLUSTER_WORKERS', '2')),
    'timeout': int(os.getenv('Q_CLUSTER_TIMEOUT', '30')),
    'retry': int(os.getenv('Q_CLUSTER_RETRY', '60')),
    'orm': os.getenv('Q_CLUSTER_ORM', 'default'),
}

# stripe api
STRIPE_API_KEY_SECRET = os.getenv('STRIPE_API_KEY_SECRET')
STRIPE_API_KEY_PUBLIC = os.getenv('STRIPE_API_KEY_PUBLIC')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET')

# logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'djangoLogger': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'formatters': {
        'verbose': {
            'format': (
                '%(asctime)s [%(levelname)s] %(pathname)s '
                '%(funcName)s.%(lineno)d | %(message)s'
            )
        },
    },
}

# django axes
AXES_FAILURE_LIMIT = int(os.getenv('AXES_FAILURE_LIMIT', '5'))
AXES_COOLOFF_TIME = timedelta(minutes=int(os.getenv('AXES_COOLOFF_TIME_MINUTES', '5')))
AXES_LOCKOUT_CALLABLE = 'clients.views.axes_locked_out'

# google reCAPTCHA
G_RECAPTCHA_KEY_SITE = os.getenv('G_RECAPTCHA_KEY_SITE')
G_RECAPTCHA_KEY_SECRET = os.getenv('G_RECAPTCHA_KEY_SECRET')
CAPTCHA_MIN_SCORE = float(os.getenv('CAPTCHA_MIN_SCORE', '0.6'))

# reservations
RESERVATION_CANCELLATION_HOURS = int(os.getenv('RESERVATION_CANCELLATION_HOURS', '24'))
CLEAN_TIME = timedelta(hours=int(os.getenv('CLEAN_TIME_HOURS', '1')))
PASSWORD_CHANGE_EMAIL_COOLDOWN = int(os.getenv('PASSWORD_CHANGE_EMAIL_COOLDOWN', '60'))
