# Generated by Django 3.2.25 on 2024-07-23 00:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=25, validators=[django.core.validators.RegexValidator('[A-Za-z]{2,25}', 'O nome deve conter apenas letras'), django.core.validators.MaxLengthValidator(25, 'Nome muito grande.'), django.core.validators.MinLengthValidator(2, 'Nome muito pequeno.')], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('[A-Za-z]{2,50}', 'O sobrenome deve conter apenas letras'), django.core.validators.MinLengthValidator(2, 'Sobrenome muito pequeno.'), django.core.validators.MaxLengthValidator(50, 'Sobrenome muito grande.')], verbose_name='Sobrenome'),
        ),
    ]
