# Generated by Django 3.2.25 on 2024-07-20 22:20

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Por favor, preencha o campo de email.', 'null': 'Por favor, preencha o campo de email.'}, max_length=255, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Informe um nome de usuário válido. O valor deve conter apenas letras, números e os seguintes caracteres @.+-_', 'unique': 'Cliente já existe.'}, max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
