# Generated by Django 5.0.6 on 2024-07-09 01:04

import clientes.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=25, validators=[clientes.validators.ValidateFieldLength('Nome', 2, 25)], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(max_length=50, validators=[clientes.validators.ValidateFieldLength('Sobrenome', 2, 50)], verbose_name='Sobrenome'),
        ),
    ]
