# Generated by Django 5.0.6 on 2024-07-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_nascimento_alter_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cliente',
            constraint=models.UniqueConstraint(fields=('nome', 'sobrenome', 'nascimento'), name='unique_client', violation_error_message='Cliente já existe.'),
        ),
    ]
