# Generated by Django 3.2.25 on 2024-07-22 02:41

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20240720_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='username',
            field=models.CharField(error_messages={'invalid': 'Informe um nome de usuário válido. O valor deve conter apenas letras, números e os seguintes caracteres @.+-_', 'unique': 'Username já existe.'}, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Nome de usuário deve ter de 2 a 150 caracteres.'), django.core.validators.MaxLengthValidator(150, 'Nome de usuário deve ter de 2 a 150 caracteres.'), django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
