# Generated by Django 5.0.6 on 2024-07-05 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, unique=True, verbose_name='Nome')),
                ('descricao_curta', models.CharField(max_length=100, unique=True, verbose_name='Descrição curta')),
            ],
            options={
                'verbose_name': 'Benefício',
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15, unique=True, verbose_name='Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField(verbose_name='Número')),
                ('capacidade', models.PositiveIntegerField(default=1, verbose_name='Capacidade')),
                ('tamanho', models.FloatField(verbose_name='Tamanho m²')),
                ('preco_diaria', models.DecimalField(decimal_places=5, max_digits=10, verbose_name='Diária')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('beneficio', models.ManyToManyField(related_name='quartos', related_query_name='quarto', to='reservas.beneficio')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quartos', related_query_name='quarto', to='reservas.classe')),
            ],
            options={
                'ordering': ['-disponivel'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(auto_now=True, verbose_name='Check-in')),
                ('checkout', models.DateField(verbose_name='Check-out')),
                ('qtd_adultos', models.PositiveIntegerField(default=1, verbose_name='Qtd. Adultos')),
                ('qtd_criancas', models.PositiveIntegerField(default=1, verbose_name='Qtd. Crianças')),
                ('observacoes', models.TextField(blank=True, max_length=100, verbose_name='Observações')),
                ('custo', models.DecimalField(blank=True, decimal_places=8, max_digits=10, verbose_name='Valor da reserva')),
                ('data_reserva', models.DateTimeField(auto_now=True, verbose_name='Data de criação da reserva')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservas', related_query_name='reserva', to='clientes.cliente')),
                ('quarto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quartos', related_query_name='quarto', to='reservas.quarto')),
            ],
            options={
                'ordering': ['-data_reserva'],
            },
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('check_in__gte', models.F('checkout'))), name='chk_checkin_gte_checkout'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('qtd_adultos__gte', 0)), name='chk_qtd_adultos_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('qtd_criancas__gte', 0)), name='chk_qtd_criancas_gte_0'),
        ),
    ]
