# Generated by Django 4.2.2 on 2023-06-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('check_in', models.DateTimeField(verbose_name='Check-in')),
                ('checkout', models.DateTimeField(verbose_name='Checkout')),
                ('quantidade_de_adultos', models.PositiveIntegerField(max_length=3, verbose_name='Qtd. Adultos')),
                ('quantidade_de_criancas', models.PositiveIntegerField(max_length=3, verbose_name='Qtd. Crianças')),
                ('tipo_de_quarto', models.CharField(choices=[('B', 'Básico'), ('L', 'Luxo'), ('V', 'VIP')], max_length=2, verbose_name='Tipo de quarto')),
                ('telefone', models.IntegerField(max_length=15, verbose_name='Telefone')),
                ('email', models.CharField(max_length=155, verbose_name='E-mail')),
                ('observacoes', models.TextField(max_length=100, verbose_name='Observações')),
            ],
        ),
    ]
