# Generated by Django 4.2.2 on 2023-06-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='quantidade_de_adultos',
            field=models.PositiveIntegerField(verbose_name='Qtd. Adultos'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quantidade_de_criancas',
            field=models.PositiveIntegerField(verbose_name='Qtd. Crianças'),
        ),
    ]
