# Generated by Django 5.0.6 on 2024-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_nascimento_alter_cliente_nome_and_more'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='chk_checkin_gte_checkout',
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='chk_qtd_adultos_gte_0',
        ),
        migrations.RemoveConstraint(
            model_name='reserva',
            name='chk_qtd_criancas_gte_0',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='custo',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Valor da reserva'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('check_in__gte', models.F('checkout'))), name='chk_checkin_gte_checkout', violation_error_message='A data de Check-in é menor que a de Check-out'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('qtd_adultos__gte', 1)), name='chk_qtd_adultos_gte_1', violation_error_message='Número de adultos inválido.'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('qtd_criancas__gte', 0)), name='chk_qtd_criancas_gte_0', violation_error_message='A quantidade de crianças não pode ser menor que 0.'),
        ),
    ]
