# Generated by Django 3.2.25 on 2024-07-19 13:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quarto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3}[A-Z]$')], verbose_name='Número')),
                ('capacidade_adultos', models.PositiveSmallIntegerField(default=1, verbose_name='Capacidade adultos')),
                ('capacidade_criancas', models.PositiveSmallIntegerField(default=1, verbose_name='Capacidade crianças')),
                ('tamanho', models.FloatField(verbose_name='Tamanho m²')),
                ('preco_diaria', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Diária')),
                ('disponivel', models.BooleanField(default=True, verbose_name='Disponível')),
                ('image', models.ImageField(blank=True, null=True, upload_to='%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Somete jpg ou png'), django.core.validators.validate_image_file_extension], verbose_name='Imagem')),
                ('short_desc', models.CharField(max_length=255, unique=True, verbose_name='Descrição curta')),
                ('long_desc', models.TextField(max_length=1000, null=True, verbose_name='Descrição longa')),
                ('beneficio', models.ManyToManyField(related_name='quarto_beneficios', related_query_name='quarto_beneficio', to='reservas.Beneficio', verbose_name='Benefícios')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quartos', related_query_name='quarto', to='reservas.classe')),
            ],
            options={
                'ordering': ['-disponivel'],
            },
        ),
    ]
