# Generated by Django 3.2.25 on 2024-07-25 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Ícone'),
        ),
    ]
