# Generated by Django 4.2.2 on 2023-06-16 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_quantidade_de_adultos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
