# Generated by Django 3.2.25 on 2024-07-25 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_beneficio_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficio',
            name='displayable_on_homepage',
            field=models.BooleanField(default=False, verbose_name='Visível na página inicial'),
        ),
    ]
