# Generated by Django 5.0.6 on 2024-07-09 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_unique_client'),
        ('reservas', '0002_remove_reserva_chk_checkin_gte_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='chk_checkin_gte_checkout',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quartos', related_query_name='quarto', to='reservas.quarto'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('check_in__gte', models.F('checkout'))), name='chk_checkin_gte_checkout', violation_error_message='A data de Check-in é maior ou igual a de Check-out'),
        ),
    ]
