# Generated by Django 4.2.2 on 2023-06-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_alter_reserva_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='check_in',
            field=models.DateField(verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='checkout',
            field=models.DateField(verbose_name='Checkout'),
        ),
    ]
