# Generated by Django 5.0.6 on 2024-07-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_unique_client'),
        ('reservas', '0003_remove_reserva_chk_checkin_gte_checkout_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reserva',
            name='chk_checkin_gte_checkout',
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('check_in__lte', models.F('checkout'))), name='chk_checkin_lte_checkout', violation_error_message='A data de Check-in é maior ou igual a de Check-out'),
        ),
    ]
