# Generated by Django 3.2.25 on 2024-07-19 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reservas', '0003_alter_quarto_long_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarto',
            name='capacidade_adultos',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5, 'Quantidade de adultos excedida. (max: 5)'), django.core.validators.MinValueValidator(1, 'Quantidade de adultos insuficiente. (min: 1)')], verbose_name='Capacidade adultos'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='capacidade_criancas',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3, 'Quantidade de crianças excedida. (max: 3)'), django.core.validators.MinValueValidator(0, 'Quantidade de crianças insuficiente. (min: 0)')], verbose_name='Capacidade crianças'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='preco_diaria',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100, 'O valor do quarto deve ser de no mínimo R$100.00.'), django.core.validators.MaxValueValidator(500, 'O valor do quarto deve ser de no máximo R$500.00.')], verbose_name='Diária'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='tamanho',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(2, 'O quarto é muito pequeno. (min: 2)'), django.core.validators.MaxValueValidator(30, 'O quarto é muito grande. (max: 30)')], verbose_name='Tamanho m²'),
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(verbose_name='Check-in')),
                ('checkout', models.DateField(verbose_name='Check-out')),
                ('qtd_adultos', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5, 'Quantidade de adultos excedida. (max: 5)'), django.core.validators.MinValueValidator(1, 'Quantidade de adultos insuficiente. (min: 1)')], verbose_name='Qtd. Adultos')),
                ('qtd_criancas', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3, 'Quantidade de crianças excedida. (max: 3)'), django.core.validators.MinValueValidator(0, 'Quantidade de crianças insuficiente. (min: 0)')], verbose_name='Qtd. Crianças')),
                ('observacoes', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('[\\w\\s]*')], verbose_name='Observações')),
                ('custo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(100)], verbose_name='Valor da reserva')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_clientes', related_query_name='reserva_cliente', to=settings.AUTH_USER_MODEL)),
                ('quarto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserva_quartos', related_query_name='reserva_quarto', to='reservas.quarto')),
            ],
        ),
    ]
