# Generated by Django 3.2.25 on 2024-07-26 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('reservas', '0004_alter_quarto_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_quartos', related_query_name='hotel_quarto', to='home.hotel'),
            preserve_default=False,
        ),
    ]
