# Generated by Django 3.2.25 on 2024-07-22 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0004_auto_20240719_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('I', 'iniciada'), ('P', 'processando'), ('C', 'concluída'), ('F', 'finalizada')], default='I', max_length=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='quarto',
            name='numero',
            field=models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^\\d{3}[A-Z]?$')], verbose_name='Número'),
        ),
    ]
