# Generated by Django 3.2.25 on 2024-07-22 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_auto_20240721_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='ativa',
            field=models.BooleanField(default=False, verbose_name='Ativa'),
        ),
    ]
