# Generated by Django 5.0.6 on 2024-07-09 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_unique_client'),
        ('reservas', '0005_remove_reserva_chk_checkin_lte_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', related_query_name='reserva', to='clientes.cliente'),
        ),
    ]
