# Generated by Django 3.2.25 on 2024-07-22 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_ativa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='qtd_adultos',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='qtd_criancas',
        ),
    ]
