# Generated by Django 5.0.6 on 2024-07-09 23:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y-%m', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], 'Somete jpg ou png'), django.core.validators.RegexValidator('^\\w+\\.(png|jpg)$')], verbose_name='Imagem'),
        ),
    ]
