# Generated by Django 3.2.25 on 2024-07-23 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_auto_20240722_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('I', 'iniciada'), ('P', 'processando'), ('C', 'cancelada'), ('F', 'finalizada')], default='I', max_length=2, verbose_name='Status'),
        ),
    ]
