# Generated by Django 5.0.6 on 2024-07-12 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0007_quarto_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_reserva',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação da reserva'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='quarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quartos', related_query_name='quarto', to='reservas.quarto'),
        ),
    ]
