# Generated by Django 3.2.25 on 2024-07-23 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_alter_reserva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criada em'),
        ),
    ]
