# Generated by Django 3.2.25 on 2024-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_reserva_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='status',
            field=models.CharField(choices=[('I', 'iniciada'), ('P', 'processando'), ('A', 'ativa'), ('C', 'cancelada'), ('F', 'finalizada')], default='I', max_length=2, verbose_name='Status'),
        ),
    ]
